CONNECT: 1 # ROS2 connection flag

PORT_OUT: 8541 # Port number for data stream out from ROS
PORT_IN: 8542 # Port number for data stream into ROS

MSG_END: "_msg_end__" # communication messege starts with this means end the port
MSG_SIZE: 55 # change the ros_side_in.hpp {boost::array<char, ...> recv_buffer_} field when chaning this number

PUBLISHER_NAME: "SimpleRos2Comm_msg_received" # Messege ROS publisher name 

VERBOSE: 1